[project]
name = "payman-zibal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "payman",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "ruff>=0.13.1",
]
